spring:
  security:
    oauth2:
      client:
        registration:

          kakao:
            client-id: 958325c348f04526a5299f91f09fc9a2
            redirect-uri: http://localhost:5943/oauth2/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email

          google:
            client-id: 873422458228-lja12vrtsjnnm9qme6b192h58qj53i47.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:5943/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#
