server:
  port: 5943

spring:
  application:
    name: hangeulbada
  profiles:
    include: oauth
  data:
    mongodb:
      uri: mongodb+srv://ssoxong:AkHS3690EwGuFD5n@cluster0.kbmk6jr.mongodb.net/Cluster0?retryWrites=true&w=majority

clova:
  ocr:
    secretkey: cFFibVZNcU1wUEdOeFNjc29QbFl2SFVzalhXTHp4b1Q=
    api:
      url: https://3xezmpp2d0.apigw.ntruss.com/custom/v1/29655/093daa40dbccc5fefb7b694abce25dcf7b21684331c8bd851807c0b85885fee2/general
