name: Run Docker Gradle

on:
  push:
    branches: [ "deploy-v2" ]
  pull_request:
    branches: [ "deploy-v2" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Stop existing application
        run: |
          if sudo lsof -t -i:5943; then
            sudo kill -9 $(sudo lsof -t -i:5943)
          fi

      - name: Execute Jar File
        run: |
          nohup java -jar /home/ubuntu/actions-runner/_work/back-end/back-end/build/libs/demo-0.0.1-SNAPSHOT.jar &
